<a href="https://colab.research.google.com/github/joseluisramon/Data-Science-Platzi/blob/master/src/03-advanced/18-manipulacion-datos-pandas/Unidad_1_Pandas_Numpy_Ventajas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso de Manipulación de Datos con Pandas - Prof. David Torres



## Unidad 1. ¿Qué es Pandas? 

Tenemos la librería Numpy

In [0]:
import numpy as np

In [0]:
np.array([1,2,3,4,5]) + 10 # numpy opera sobre todo el arreglo

array([11, 12, 13, 14, 15])

In [0]:
np.array([2,3,4,5,6]).shape # vectores

(5,)

In [0]:
np.array([[1,2,3,4],[5,6,7,8]]).shape # matrices (listas dentro de listas)

(2, 4)

In [0]:
np.array([[1,2,3,4,],[5,6,7,8]] )[0] 

array([1, 2, 3, 4])

In [0]:
np.array([[1,2,3,4,],[5,6,7,8]] )[0][1] 

2

In [0]:
np.array([[1,2,3,4,],[5,6,7,8]]) + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

Tenemos la librería Pandas

In [0]:
import pandas as pd

In [21]:
sr = pd.Series([10,9,8,7,6]) #elementos series. Es un elemento que tiene indexación
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [22]:
sr.values

array([10,  9,  8,  7,  6])

In [23]:
sr.index #esto nos da información acerca del rango del objeto

RangeIndex(start=0, stop=5, step=1)

In [24]:
sr.shape

(5,)

In [25]:
sr[3] # te puedes guiar con la indexación

7

In [29]:
sr[[0,4,2]] # puedes seleccionar valores específicos y 

0    10
4     6
2     8
dtype: int64