<a href="https://colab.research.google.com/github/joseluisramon/Data-Science-Platzi/blob/master/src/03-advanced/18-manipulacion-datos-pandas/Unidad_1_Pandas_Numpy_Ventajas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso de Manipulación de Datos con Pandas - Prof. David Torres



## Unidad 1. ¿Qué es Pandas? 

Tenemos la librería Numpy

In [0]:
import numpy as np

In [0]:
np.array([1,2,3,4,5]) + 10 # numpy opera sobre todo el arreglo

array([11, 12, 13, 14, 15])

In [0]:
np.array([2,3,4,5,6]).shape # vectores

(5,)

In [0]:
np.array([[1,2,3,4],[5,6,7,8]]).shape # matrices (listas dentro de listas)

(2, 4)

In [0]:
np.array([[1,2,3,4,],[5,6,7,8]] )[0] 

array([1, 2, 3, 4])

In [0]:
np.array([[1,2,3,4,],[5,6,7,8]] )[0][1] 

2

In [0]:
np.array([[1,2,3,4,],[5,6,7,8]]) + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

Tenemos la librería Pandas

In [0]:
import pandas as pd

In [21]:
sr = pd.Series([10,9,8,7,6]) #elementos series. Es un elemento que tiene indexación
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [22]:
sr.values

array([10,  9,  8,  7,  6])

In [23]:
sr.index #esto nos da información acerca del rango del objeto

RangeIndex(start=0, stop=5, step=1)

In [24]:
sr.shape

(5,)

In [25]:
sr[3] # te puedes guiar con la indexación

7

In [29]:
sr[[0,4,2]] # puedes seleccionar valores específicos dentro de una lista 

0    10
4     6
2     8
dtype: int64

In [36]:
r = pd.Series([10,9,8,7,6], index = ['a','b','c','d','e']) # se le pueden asignar índices específicos
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [38]:
sr[['c','e']] # puedo traer valores e indices. Es parecido a los dict de Python

c    8
e    6
dtype: int64

In [41]:
dict_data = {'CO':100, 'MX':200, 'AR':300} # los diccionarios siguen un formato similar a JSON
dict_data.keys(), dict_data.values()

(dict_keys(['CO', 'MX', 'AR']), dict_values([100, 200, 300]))

In [42]:
pd.Series(dict_data) # Pero que sorpresa! Pandas es compatibles con diccionarios

CO    100
MX    200
AR    300
dtype: int64

In [48]:
sr = pd.Series(dict_data, index=['CO','MX','PE','AR'])
sr
# puedes definir nuevos elementos pero tendrán valores vacíos por no estar definidos previamente

CO    100.0
MX    200.0
PE      NaN
AR    300.0
dtype: float64

Es importante conocer como funcionan los valores nulos para cuando se haga extracción desde una base de datos sabes que pasa con los valores nulos

In [44]:
np.nan # objeto nulo de Numpy
np.nan + 10 # observamos que las oepraciones aritméticas sobre un valor nulo dan resultado nulo

nan

In [49]:
# Pandas tiene un método para definir cuales valor son nulos
sr.isnull()

CO    False
MX    False
PE     True
AR    False
dtype: bool

In [50]:
# Pandas tiene otra función equivalente para los valores no nulos
sr.notnull()

CO     True
MX     True
PE    False
AR     True
dtype: bool